CONECTANDO SQL COM PANDAS

In [8]:
import sqlite3
import pandas as pd

conecxao = sqlite3.connect('status_brasil')

In [2]:
import os
print(os.getcwd())  # mostra o diretório atual

c:\Users\vkere\OneDrive\Documentos\GitHub\ProgrAmo---Analise-de-Dados\Modulo5

In [12]:
query = "SELECT * FROM Municipios_Brasileiros WHERE Cidade = 'Itaquaquecetuba';"

In [13]:
query

"SELECT * FROM Municipios_Brasileiros WHERE Cidade = 'Itaquaquecetuba';"

In [14]:
pd.read_sql(query, con=conecxao)

            Cidade Estado   Regiao  municipio_ID
0  Itaquaquecetuba     SP  Sudeste          5043

In [ ]:
query ='''SELECT Municipios_Brasileiros.Estado, AVG(Municipio_Status.renda) FROM Municipios_Brasileiros                          INNER JOIN Municipio_Status ON Municipios_Brasileiros.municipio_ID = Municipio_Status.municipio_ID                                     
WHERE Municipios_Brasileiros IN lista_estados
GROUP BY Municipios_Brasileiros.Estado;'''
#AVG calcula a média

In [19]:
pd.read_sql(query, con=conecxao)

   Estado  AVG(Municipio_Status.renda)
0      AC                     0.585455
1      AL                     0.548363
2      AM                     0.545113
3      AP                     0.618875
4      BA                     0.574805
5      CE                     0.559293
6      DF                     0.863000
7      ES                     0.680628
8      GO                     0.683980
9      MA                     0.531664
10     MG                     0.652008
11     MS                     0.687846
12     MT                     0.682149
13     PA                     0.572357
14     PB                     0.564423
15     PE                     0.574378
16     PI                     0.546813
17     PR                     0.691915
18     RJ                     0.704796
19     RN                     0.580183
20     RO                     0.658173
21     RR                     0.577867
22     RS                     0.722115
23     SC                     0.728038
24     SE                     0.577147
25     SP                     0.716571
26     TO                     0.610543

In [25]:

import pandas as pd
dados2 = pd.read_excel('../Modulo4/Planilha_Aula_parte2.xlsx')
dados = pd.read_excel("../Modulo3/planilha_modulo3.xlsx")
dados = dados.merge(dados2, on='ID', how='left')

In [30]:
lista_estados = list(dados['UF ONDE MORA'].unique())